Fixed a runtime error that prevented the website from loading because the pacman loader (sass) reference failing. The error was caused by a typo in Apps.scss for the loader import
Line 4 error:
error:      @import '~loaders.css/ '
correction: @import 'loaders.css/ '